### ISSUE TITLE
Issue with CVP.yml Configlet Assignment

### ISSUE THREAD

**Issue by DimitriCapetz** [tonybourkesdnpros/Level5-Ansible-CVP#1]
In executing the labs, I noticed that there is an error in the CVP.yml file for the ACE L5 labs.  The configlet assignment for spine1-DC2 is mistakenly set as leaf1-DC2.

```
  spine1-DC2:
    name: 'spine1-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf1-DC2-BASE'
```

Should be...

```
  spine1-DC2:
    name: 'spine1-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'spine1-DC2-BASE'
```

Also, it is worth noting that the ATD-INFRA configlet it assigned in CVP at the Tenant container level so there is no need to apply it to the device level and it can safely be removed from this yaml file.
